name: daily_run

# Controls when the workflow will run
on:

  schedule:
   - cron: '0 */12 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORK_TOKEN }}
    
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install tabulate
          pip install lxml
          pip install requests
      - name: ls_show
        run: |
          python sp500.py
          ls -al *.csv
             
      - name: Push changes to remote repository
        env:
          U_NAME: ${{ secrets.U_NAME }}
          U_EMAIL: ${{ secrets.U_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.WORK_TOKEN }}
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
          pwd
          git config --local user.name "${U_NAME}"  
          git config --local user.email "${U_EMAIL}" 

          git status -s
          git add *.csv
          git add .github/workflows/daily_run.yml
          git add README.md

          git commit -m "Github SP500 Constituents Auto Renew at `date +'%Y-%m-%d %H:%M'`"

          echo "======git push===="
          git push --force origin main
          else
          echo "No changes, skip push."
          fi
